services:
  postgres-test:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password
      POSTGRES_DB: todo_db_test
    ports:
      - '5434:5432'
    volumes:
      - todo-postgres-test:/var/lib/postgresql/data

  todo-api-test:
    build: .
    env_file:
      - .env.test
    depends_on:
      - postgres-test
    command: npm run test

volumes:
  todo-postgres-test:
