version: '3.8'

services:
  db:
    image: postgres:15
    container_name: todo-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_db
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: todo-api
    restart: always
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - db

volumes:
  pgdata:
