services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password
      POSTGRES_DB: todo_db
    ports:
      - '5433:5432'
    volumes:
      - todo-postgres:/var/lib/postgresql/data

  todo-api:
    build: .
    container_name: todo-api
    restart: unless-stopped
    env_file:
      - .env
      - .env.docker
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

volumes:
  todo-postgres:
